environment:
  PYTHON: "C:\\Python27"
  JAVA_HOME: C:\Program Files\Java\jdk1.7.0\

install:
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - "%PYTHON%/Scripts/pip.exe install codecov"

test_script:
  - mvn test

cache:
  - '%HOMEPATH%\.m2' 

build: off