environment:
  PYTHON: "C:\\Python27"

install:
  - cmd: java -version
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
  - "%PYTHON%/Scripts/pip.exe install codecov"

test_script:
  - mvn test

cache:
  - '%HOMEPATH%\.m2' 

build: off